apiVersion: v1
kind: Service
metadata:
  name: debugger
spec:
  selector:
    app: debugger
  ports:
  - port: 80
    name: "http"
    targetPort: 80
  - port: 5000
    name: "http-debug"
    targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debugger
  labels:
    app: debugger
spec:
  selector:
    matchLabels:
      app: debugger
  template:
    metadata:
      labels:
        app: debugger
    spec:
      containers:
      - name: debugger
        image: mcr.microsoft.com/dotnet/aspnet:6.0
        command: ["sleep", "7200"]
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Development"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        - containerPort: 80

