apiVersion: v1
kind: Service
metadata:
  name: deployer
spec:
  selector:
    app: deployer
  ports:
  - port: 80
    name: "http"
    targetPort: 80
  - port: 443
    name: "https"
    targetPort: 443
  - port: 5000
    name: "http-debug"
    targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployer
  labels:
    app: deployer
spec:
  selector:
    matchLabels:
      app: deployer
  template:
    metadata:
      labels:
        app: deployer
    spec:
      containers:
      - name: deployer
        image: tiegris/k8s-monitor-core:latest
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Development"
        resources:
          limits:
            memory: "300Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        - containerPort: 80
        - containerPort: 443

