apiVersion: v1
kind: Service
metadata:
  name: wait-1
  annotations:
    mnet.uri.scheme: "http://"
    mnet.uri.port: "80"
    mnet.uri.path: "/Wait"
    mnet.timeout: "5"
    mnet.period: "10"
    mnet.failureThreshold: "3"
    mnet.hpa.enabled: "true"
    mnet.hpa.percentage: "60"
spec:
  selector:
    app: wait-1
  ports:
  - port: 9000
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-1
  annotations:
    mnet.uri.path: "Wait"
spec:
  selector:
    app: dummy-1
  ports:
  - port: 9001
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-2
  annotations:
    mnet.uri.path: "Wait"
spec:
  selector:
    app: dummy-2
  ports:
  - port: 9001
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-3
  annotations:
    mnet.uri.path: "Wait"
spec:
  selector:
    app: dummy-3
  ports:
  - port: 9001
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-4
  annotations:
    mnet.uri.path: "Wait"
spec:
  selector:
    app: dummy-4
  ports:
  - port: 9001
    targetPort: 80
