apiVersion: v1
kind: Service
metadata:
  name: dummy-1
  annotations:
    mnet.uri.path: "Wait"
    mnet.uri.port: "900000"
spec:
  selector:
    app: dummy-1
  ports:
  - port: 9001
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-2
  annotations:
    mnet.uri.path: "Wait"
spec:
  selector:
    app: dummy-2
  ports:
  - port: 9001
    targetPort: 80
