name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Build the Docker image
      run: docker build ./main/K8sMonitorCore --file ./main/K8sMonitorCore/K8sMonitorCore/Dockerfile --tag tiegris/k8s-monitor-core:latest
        
    - name: Build and push
      run: docker build push tiegris/k8s-monitor-core:latest
